// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Database;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.MedkitModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("bandage")
                        .HasColumnType("int");

                    b.Property<int>("bloodsucker")
                        .HasColumnType("int");

                    b.Property<double>("cord_x")
                        .HasColumnType("float");

                    b.Property<double>("cord_y")
                        .HasColumnType("float");

                    b.Property<int>("dust_wound")
                        .HasColumnType("int");

                    b.Property<int>("elastric")
                        .HasColumnType("int");

                    b.Property<int>("foil_nrc")
                        .HasColumnType("int");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("latex")
                        .HasColumnType("int");

                    b.Property<int>("mask")
                        .HasColumnType("int");

                    b.Property<int>("medpack")
                        .HasColumnType("int");

                    b.Property<int>("plaster")
                        .HasColumnType("int");

                    b.Property<int>("plaster_mark")
                        .HasColumnType("int");

                    b.Property<int>("plaster_mark_2")
                        .HasColumnType("int");

                    b.Property<int>("spirit")
                        .HasColumnType("int");

                    b.Property<int>("splint")
                        .HasColumnType("int");

                    b.Property<string>("uwaga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Medkit");
                });

            modelBuilder.Entity("WebApplication1.Models.RegisterModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("privelage")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
